name: wai-middleware-json-errors
version: '0.1.0'
category: Web
author: Sean Hess
maintainer: seanhess@gmail.com
copyright: Orbital Labs
license: BSD3
github: orbital/wai-middleware-json-errors
extra-source-files:
- README.md

dependencies:
- aeson
- binary
- bytestring
- http-types
- text
- wai

library:
  source-dirs: src
  exposed-modules:
  - Network.Wai.Middleware.JsonErrors
  dependencies:
  - base >=4.7 && <5
tests:
  wai-middleware-json-errors-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - wai-middleware-json-errors
